# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40390d43bddb624c243cf0aaa3cba4f49c21dc8c639c45c73c253084c4532177dcc3d15963fc6ee986e6b72428d1034c1709479e9620f63d2f93f3bf77c915af

test:
  secret_key_base: 396562440bee92420322b42b579fee42bd3743f18998e7b1c2c896d7b61092be8ce3f87a143ec061e42e7622a57fd60e4dfa0782dfdec8922796ef39d444171e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
